version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: electrician-postgres
    environment:
      POSTGRES_DB: electrician_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: extrimepasswd
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - electrician-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: electrician-app
    ports:
      - "80:80"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/electrician_db # amvera-extrime-cnpg-electricdbextreme-rw
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: extrimepasswd
      SPRING_APPLICATION_URL: https://0.0.0.0:80/
      SERVER_PORT: 80
      SPRING_MAIL_USERNAME: electric252.com@gmail.com
      SPRING_MAIL_PASSWORD: ntvf auqn hksz uham
      FILE_UPLOAD_DIR: /app/uploads
    volumes:
      - uploads_volume:/app/uploads
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - electrician-network
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP порт
      - "8025:8025"  # Web UI

  electrician-app:
    depends_on:
      - mailhog

networks:
  electrician-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  uploads_volume:
    driver: local