spring:
  application:
    name: electrician-service
    url: ${SERVER_URL}
    domain: ${SERVER_DOMAIN}

  # POSTGRES
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # postgres: validate update create create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # postgres
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  # Отключение кэша статических ресурсов
  web:
    resources:
      static-locations: classpath:/static/, file:${FILE_UPLOAD_DIR:./uploads}/
      cache:
        period: 0  # Отключает кэш браузера для статических ресурсов
        cachecontrol:
          no-cache: true
          must-revalidate: true
      add-mappings: false

  # Отключение кэша шаблонов Spring MVC
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
      throw-exception-if-no-handler-found: false

  # Загрузка файлов
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2KB

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}  # Ваш Gmail
    password: ${MAIL_PASSWORD}  # Пароль приложения (не основной пароль)
    port: ${MAIL_PORT} # 587 465 8025
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


# Настройки верификации email
email:
  verification:
    code-length: 6
    expiration-minutes: 5
    sender-name: ${MAIL_SENDER}
    subject: "Код подтверждения регистрации"


server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    path: /error


# Настройки для телеграм бота
telegram:
  TOKEN: ${TELEGRAM_TOKEN}
  OWNER_ID: ${TELEGRAM_OWNER_ID}
  CHANNEL_ID: ${TELEGRAM_CHANNEL_ID}
  INVITE_LINK: ${TELEGRAM_INVITE_LINK}


logging:
  level:
    com.extrime.electrician: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG
    org:springframework:jdbc: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
  file:
    name: /app/logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"