spring:
  application:
    name: electrician-service
    url: ${SPRING_APPLICATION_URL:http://0.0.0.0:8081/}
    domain: http://электрик252.рф/

  # POSTGRES
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/electrician_db}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/electrician_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:extrimepasswd}

  jpa:
    hibernate:
      ddl-auto: update # postgres: validate update create create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # postgres
        format_sql: true

#  MySQL
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/electrician_db
#    username: root
#    password: extrimepasswd
#  MySQL
#  jpa:
#    hibernate:
#      ddl-auto: validate # postgres
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect # postgres
#        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  # Отключение кэша статических ресурсов
  web:
    resources:
      static-locations: classpath:/static/, file:${FILE_UPLOAD_DIR:./uploads}/
      cache:
        period: 0  # Отключает кэш браузера для статических ресурсов
        cachecontrol:
          no-cache: true
          must-revalidate: true
      add-mappings: false

  # Отключение кэша шаблонов Spring MVC
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
      throw-exception-if-no-handler-found: false

  # Загрузка файлов
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2KB

  mail:
    host: smtp.gmail.com
    port: 587 # 587 465 8025
    username: ${SPRING_MAIL_USERNAME:electric252.com@gmail.com}  # Ваш Gmail
    password: ${SPRING_MAIL_PASSWORD:ntvf auqn hksz uham}     # Пароль приложения (не основной пароль)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


# Настройки верификации email
email:
  verification:
    code-length: 6
    expiration-minutes: 5
    sender-name: "Электрик Сервис"
    subject: "Код подтверждения регистрации"


server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    path: /error


logging:
  level:
    com.extrime.electrician: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG
    org:springframework:jdbc: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
  file:
    name: /app/logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"