spring:
  application:
    name: electrician-service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/electrician_db
    username: postgres
    password: extrimepasswd

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Отключение кэша статических ресурсов
  web:
    resources:
      static-locations: classpath:/static/, file:./uploads/
      cache:
        period: 0  # Отключает кэш браузера для статических ресурсов
        cachecontrol:
          no-cache: true
          must-revalidate: true

  # Отключение кэша шаблонов Spring MVC
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html

  # Загрузка файлов
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2KB

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    com.extrime.electrician: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE