spring:
  application:
    name: electrician-service
    url: localhost
#    url: http://электрик252.рф

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/electrician_db
    username: postgres
    password: extrimepasswd

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Отключение кэша статических ресурсов
  web:
    resources:
      static-locations: classpath:/static/, file:./uploads/
      cache:
        period: 0  # Отключает кэш браузера для статических ресурсов
        cachecontrol:
          no-cache: true
          must-revalidate: true
      add-mappings: false

  # Отключение кэша шаблонов Spring MVC
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
      throw-exception-if-no-handler-found: false

  # Загрузка файлов
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2KB

  mail:
    host: smtp.gmail.com
    port: 587
    username: timurmalishevxt57@gmail.com  # Ваш Gmail
    password: iqpp dswl lhmo qgsu     # Пароль приложения (не основной пароль)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


# Настройки верификации email
email:
  verification:
    code-length: 6
    expiration-minutes: 5
    sender-name: "Электрик Сервис"
    subject: "Код подтверждения регистрации"


server:
  port: 8081
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    path: /error


logging:
  level:
    com.extrime.electrician: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG
    org:springframework:jdbc: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE